/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsXraySystemConfigRouteImport } from './routes/docs/xray-system-config'
import { Route as DocsXrayServiceRouteImport } from './routes/docs/xray-service'
import { Route as DocsXrayRoutingRouteImport } from './routes/docs/xray-routing'
import { Route as DocsXrayOutboundsRouteImport } from './routes/docs/xray-outbounds'
import { Route as DocsXrayInboundsRouteImport } from './routes/docs/xray-inbounds'
import { Route as DocsWebsiteManagementRouteImport } from './routes/docs/website-management'
import { Route as DocsUsersRouteImport } from './routes/docs/users'
import { Route as DocsUpgradeFromMmwRouteImport } from './routes/docs/upgrade-from-mmw'
import { Route as DocsUpdateRouteImport } from './routes/docs/update'
import { Route as DocsTutorialRouteImport } from './routes/docs/tutorial'
import { Route as DocsToolMmwxTgbotRouteImport } from './routes/docs/tool-mmwx-tgbot'
import { Route as DocsToolCloudflareTurnstileRouteImport } from './routes/docs/tool-cloudflare-turnstile'
import { Route as DocsTemplatesRouteImport } from './routes/docs/templates'
import { Route as DocsSystemSettingsRouteImport } from './routes/docs/system-settings'
import { Route as DocsSystemRequirementsRouteImport } from './routes/docs/system-requirements'
import { Route as DocsSubscribeFilesRouteImport } from './routes/docs/subscribe-files'
import { Route as DocsShareServerRouteImport } from './routes/docs/share-server'
import { Route as DocsRoutedOutboundRouteImport } from './routes/docs/routed-outbound'
import { Route as DocsRemoteServersRouteImport } from './routes/docs/remote-servers'
import { Route as DocsQuickStartRouteImport } from './routes/docs/quick-start'
import { Route as DocsProtocolVmessRouteImport } from './routes/docs/protocol-vmess'
import { Route as DocsProtocolVlessRouteImport } from './routes/docs/protocol-vless'
import { Route as DocsProtocolTrojanRouteImport } from './routes/docs/protocol-trojan'
import { Route as DocsProtocolSnellRouteImport } from './routes/docs/protocol-snell'
import { Route as DocsProtocolShadowsocksRouteImport } from './routes/docs/protocol-shadowsocks'
import { Route as DocsProtocolMatrixRouteImport } from './routes/docs/protocol-matrix'
import { Route as DocsProtocolHysteria2RouteImport } from './routes/docs/protocol-hysteria2'
import { Route as DocsProtocolAnytlsRouteImport } from './routes/docs/protocol-anytls'
import { Route as DocsProbeApiRouteImport } from './routes/docs/probe-api'
import { Route as DocsPackagesRouteImport } from './routes/docs/packages'
import { Route as DocsNodesRouteImport } from './routes/docs/nodes'
import { Route as DocsNodeSpeedtestRouteImport } from './routes/docs/node-speedtest'
import { Route as DocsNodeRatelimitRouteImport } from './routes/docs/node-ratelimit'
import { Route as DocsMcpRouteImport } from './routes/docs/mcp'
import { Route as DocsInstallExternalProbeRouteImport } from './routes/docs/install-external-probe'
import { Route as DocsInstallDockerRouteImport } from './routes/docs/install-docker'
import { Route as DocsInstallDirectRouteImport } from './routes/docs/install-direct'
import { Route as DocsInstallAgentRouteImport } from './routes/docs/install-agent'
import { Route as DocsGeneratorRouteImport } from './routes/docs/generator'
import { Route as DocsFeaturesRouteImport } from './routes/docs/features'
import { Route as DocsFaqSubClientRouteImport } from './routes/docs/faq-sub-client'
import { Route as DocsFaqServerManagementRouteImport } from './routes/docs/faq-server-management'
import { Route as DocsFaqProtocolInboundRouteImport } from './routes/docs/faq-protocol-inbound'
import { Route as DocsFaqNodeManagementRouteImport } from './routes/docs/faq-node-management'
import { Route as DocsFaqInstallDeployRouteImport } from './routes/docs/faq-install-deploy'
import { Route as DocsFaqCommonOpsRouteImport } from './routes/docs/faq-common-ops'
import { Route as DocsFaqCarpoolRouteImport } from './routes/docs/faq-carpool'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsEmbeddedXrayRouteImport } from './routes/docs/embedded-xray'
import { Route as DocsCustomRulesRouteImport } from './routes/docs/custom-rules'
import { Route as DocsComparisonRouteImport } from './routes/docs/comparison'
import { Route as DocsChangelogRouteImport } from './routes/docs/changelog'
import { Route as DocsCertificatesRouteImport } from './routes/docs/certificates'
import { Route as DocsBackupRestoreRouteImport } from './routes/docs/backup-restore'
import { Route as DocsAboutRouteImport } from './routes/docs/about'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsXraySystemConfigRoute = DocsXraySystemConfigRouteImport.update({
  id: '/xray-system-config',
  path: '/xray-system-config',
  getParentRoute: () => DocsRoute,
} as any)
const DocsXrayServiceRoute = DocsXrayServiceRouteImport.update({
  id: '/xray-service',
  path: '/xray-service',
  getParentRoute: () => DocsRoute,
} as any)
const DocsXrayRoutingRoute = DocsXrayRoutingRouteImport.update({
  id: '/xray-routing',
  path: '/xray-routing',
  getParentRoute: () => DocsRoute,
} as any)
const DocsXrayOutboundsRoute = DocsXrayOutboundsRouteImport.update({
  id: '/xray-outbounds',
  path: '/xray-outbounds',
  getParentRoute: () => DocsRoute,
} as any)
const DocsXrayInboundsRoute = DocsXrayInboundsRouteImport.update({
  id: '/xray-inbounds',
  path: '/xray-inbounds',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWebsiteManagementRoute = DocsWebsiteManagementRouteImport.update({
  id: '/website-management',
  path: '/website-management',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUsersRoute = DocsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUpgradeFromMmwRoute = DocsUpgradeFromMmwRouteImport.update({
  id: '/upgrade-from-mmw',
  path: '/upgrade-from-mmw',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUpdateRoute = DocsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTutorialRoute = DocsTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => DocsRoute,
} as any)
const DocsToolMmwxTgbotRoute = DocsToolMmwxTgbotRouteImport.update({
  id: '/tool-mmwx-tgbot',
  path: '/tool-mmwx-tgbot',
  getParentRoute: () => DocsRoute,
} as any)
const DocsToolCloudflareTurnstileRoute =
  DocsToolCloudflareTurnstileRouteImport.update({
    id: '/tool-cloudflare-turnstile',
    path: '/tool-cloudflare-turnstile',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsTemplatesRoute = DocsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSystemSettingsRoute = DocsSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSystemRequirementsRoute = DocsSystemRequirementsRouteImport.update({
  id: '/system-requirements',
  path: '/system-requirements',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSubscribeFilesRoute = DocsSubscribeFilesRouteImport.update({
  id: '/subscribe-files',
  path: '/subscribe-files',
  getParentRoute: () => DocsRoute,
} as any)
const DocsShareServerRoute = DocsShareServerRouteImport.update({
  id: '/share-server',
  path: '/share-server',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRoutedOutboundRoute = DocsRoutedOutboundRouteImport.update({
  id: '/routed-outbound',
  path: '/routed-outbound',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRemoteServersRoute = DocsRemoteServersRouteImport.update({
  id: '/remote-servers',
  path: '/remote-servers',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolVmessRoute = DocsProtocolVmessRouteImport.update({
  id: '/protocol-vmess',
  path: '/protocol-vmess',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolVlessRoute = DocsProtocolVlessRouteImport.update({
  id: '/protocol-vless',
  path: '/protocol-vless',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolTrojanRoute = DocsProtocolTrojanRouteImport.update({
  id: '/protocol-trojan',
  path: '/protocol-trojan',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolSnellRoute = DocsProtocolSnellRouteImport.update({
  id: '/protocol-snell',
  path: '/protocol-snell',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolShadowsocksRoute = DocsProtocolShadowsocksRouteImport.update({
  id: '/protocol-shadowsocks',
  path: '/protocol-shadowsocks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolMatrixRoute = DocsProtocolMatrixRouteImport.update({
  id: '/protocol-matrix',
  path: '/protocol-matrix',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolHysteria2Route = DocsProtocolHysteria2RouteImport.update({
  id: '/protocol-hysteria2',
  path: '/protocol-hysteria2',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProtocolAnytlsRoute = DocsProtocolAnytlsRouteImport.update({
  id: '/protocol-anytls',
  path: '/protocol-anytls',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProbeApiRoute = DocsProbeApiRouteImport.update({
  id: '/probe-api',
  path: '/probe-api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPackagesRoute = DocsPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNodesRoute = DocsNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNodeSpeedtestRoute = DocsNodeSpeedtestRouteImport.update({
  id: '/node-speedtest',
  path: '/node-speedtest',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNodeRatelimitRoute = DocsNodeRatelimitRouteImport.update({
  id: '/node-ratelimit',
  path: '/node-ratelimit',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallExternalProbeRoute =
  DocsInstallExternalProbeRouteImport.update({
    id: '/install-external-probe',
    path: '/install-external-probe',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsInstallDockerRoute = DocsInstallDockerRouteImport.update({
  id: '/install-docker',
  path: '/install-docker',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallDirectRoute = DocsInstallDirectRouteImport.update({
  id: '/install-direct',
  path: '/install-direct',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallAgentRoute = DocsInstallAgentRouteImport.update({
  id: '/install-agent',
  path: '/install-agent',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGeneratorRoute = DocsGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesRoute = DocsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqSubClientRoute = DocsFaqSubClientRouteImport.update({
  id: '/faq-sub-client',
  path: '/faq-sub-client',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqServerManagementRoute = DocsFaqServerManagementRouteImport.update({
  id: '/faq-server-management',
  path: '/faq-server-management',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqProtocolInboundRoute = DocsFaqProtocolInboundRouteImport.update({
  id: '/faq-protocol-inbound',
  path: '/faq-protocol-inbound',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqNodeManagementRoute = DocsFaqNodeManagementRouteImport.update({
  id: '/faq-node-management',
  path: '/faq-node-management',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqInstallDeployRoute = DocsFaqInstallDeployRouteImport.update({
  id: '/faq-install-deploy',
  path: '/faq-install-deploy',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqCommonOpsRoute = DocsFaqCommonOpsRouteImport.update({
  id: '/faq-common-ops',
  path: '/faq-common-ops',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqCarpoolRoute = DocsFaqCarpoolRouteImport.update({
  id: '/faq-carpool',
  path: '/faq-carpool',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEmbeddedXrayRoute = DocsEmbeddedXrayRouteImport.update({
  id: '/embedded-xray',
  path: '/embedded-xray',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomRulesRoute = DocsCustomRulesRouteImport.update({
  id: '/custom-rules',
  path: '/custom-rules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComparisonRoute = DocsComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCertificatesRoute = DocsCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBackupRestoreRoute = DocsBackupRestoreRouteImport.update({
  id: '/backup-restore',
  path: '/backup-restore',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAboutRoute = DocsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/about': typeof DocsAboutRoute
  '/docs/backup-restore': typeof DocsBackupRestoreRoute
  '/docs/certificates': typeof DocsCertificatesRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/comparison': typeof DocsComparisonRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/embedded-xray': typeof DocsEmbeddedXrayRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/faq-carpool': typeof DocsFaqCarpoolRoute
  '/docs/faq-common-ops': typeof DocsFaqCommonOpsRoute
  '/docs/faq-install-deploy': typeof DocsFaqInstallDeployRoute
  '/docs/faq-node-management': typeof DocsFaqNodeManagementRoute
  '/docs/faq-protocol-inbound': typeof DocsFaqProtocolInboundRoute
  '/docs/faq-server-management': typeof DocsFaqServerManagementRoute
  '/docs/faq-sub-client': typeof DocsFaqSubClientRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/install-agent': typeof DocsInstallAgentRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/install-external-probe': typeof DocsInstallExternalProbeRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/node-ratelimit': typeof DocsNodeRatelimitRoute
  '/docs/node-speedtest': typeof DocsNodeSpeedtestRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/packages': typeof DocsPackagesRoute
  '/docs/probe-api': typeof DocsProbeApiRoute
  '/docs/protocol-anytls': typeof DocsProtocolAnytlsRoute
  '/docs/protocol-hysteria2': typeof DocsProtocolHysteria2Route
  '/docs/protocol-matrix': typeof DocsProtocolMatrixRoute
  '/docs/protocol-shadowsocks': typeof DocsProtocolShadowsocksRoute
  '/docs/protocol-snell': typeof DocsProtocolSnellRoute
  '/docs/protocol-trojan': typeof DocsProtocolTrojanRoute
  '/docs/protocol-vless': typeof DocsProtocolVlessRoute
  '/docs/protocol-vmess': typeof DocsProtocolVmessRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/remote-servers': typeof DocsRemoteServersRoute
  '/docs/routed-outbound': typeof DocsRoutedOutboundRoute
  '/docs/share-server': typeof DocsShareServerRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/tool-cloudflare-turnstile': typeof DocsToolCloudflareTurnstileRoute
  '/docs/tool-mmwx-tgbot': typeof DocsToolMmwxTgbotRoute
  '/docs/tutorial': typeof DocsTutorialRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/upgrade-from-mmw': typeof DocsUpgradeFromMmwRoute
  '/docs/users': typeof DocsUsersRoute
  '/docs/website-management': typeof DocsWebsiteManagementRoute
  '/docs/xray-inbounds': typeof DocsXrayInboundsRoute
  '/docs/xray-outbounds': typeof DocsXrayOutboundsRoute
  '/docs/xray-routing': typeof DocsXrayRoutingRoute
  '/docs/xray-service': typeof DocsXrayServiceRoute
  '/docs/xray-system-config': typeof DocsXraySystemConfigRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/about': typeof DocsAboutRoute
  '/docs/backup-restore': typeof DocsBackupRestoreRoute
  '/docs/certificates': typeof DocsCertificatesRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/comparison': typeof DocsComparisonRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/embedded-xray': typeof DocsEmbeddedXrayRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/faq-carpool': typeof DocsFaqCarpoolRoute
  '/docs/faq-common-ops': typeof DocsFaqCommonOpsRoute
  '/docs/faq-install-deploy': typeof DocsFaqInstallDeployRoute
  '/docs/faq-node-management': typeof DocsFaqNodeManagementRoute
  '/docs/faq-protocol-inbound': typeof DocsFaqProtocolInboundRoute
  '/docs/faq-server-management': typeof DocsFaqServerManagementRoute
  '/docs/faq-sub-client': typeof DocsFaqSubClientRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/install-agent': typeof DocsInstallAgentRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/install-external-probe': typeof DocsInstallExternalProbeRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/node-ratelimit': typeof DocsNodeRatelimitRoute
  '/docs/node-speedtest': typeof DocsNodeSpeedtestRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/packages': typeof DocsPackagesRoute
  '/docs/probe-api': typeof DocsProbeApiRoute
  '/docs/protocol-anytls': typeof DocsProtocolAnytlsRoute
  '/docs/protocol-hysteria2': typeof DocsProtocolHysteria2Route
  '/docs/protocol-matrix': typeof DocsProtocolMatrixRoute
  '/docs/protocol-shadowsocks': typeof DocsProtocolShadowsocksRoute
  '/docs/protocol-snell': typeof DocsProtocolSnellRoute
  '/docs/protocol-trojan': typeof DocsProtocolTrojanRoute
  '/docs/protocol-vless': typeof DocsProtocolVlessRoute
  '/docs/protocol-vmess': typeof DocsProtocolVmessRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/remote-servers': typeof DocsRemoteServersRoute
  '/docs/routed-outbound': typeof DocsRoutedOutboundRoute
  '/docs/share-server': typeof DocsShareServerRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/tool-cloudflare-turnstile': typeof DocsToolCloudflareTurnstileRoute
  '/docs/tool-mmwx-tgbot': typeof DocsToolMmwxTgbotRoute
  '/docs/tutorial': typeof DocsTutorialRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/upgrade-from-mmw': typeof DocsUpgradeFromMmwRoute
  '/docs/users': typeof DocsUsersRoute
  '/docs/website-management': typeof DocsWebsiteManagementRoute
  '/docs/xray-inbounds': typeof DocsXrayInboundsRoute
  '/docs/xray-outbounds': typeof DocsXrayOutboundsRoute
  '/docs/xray-routing': typeof DocsXrayRoutingRoute
  '/docs/xray-service': typeof DocsXrayServiceRoute
  '/docs/xray-system-config': typeof DocsXraySystemConfigRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/about': typeof DocsAboutRoute
  '/docs/backup-restore': typeof DocsBackupRestoreRoute
  '/docs/certificates': typeof DocsCertificatesRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/comparison': typeof DocsComparisonRoute
  '/docs/custom-rules': typeof DocsCustomRulesRoute
  '/docs/embedded-xray': typeof DocsEmbeddedXrayRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/faq-carpool': typeof DocsFaqCarpoolRoute
  '/docs/faq-common-ops': typeof DocsFaqCommonOpsRoute
  '/docs/faq-install-deploy': typeof DocsFaqInstallDeployRoute
  '/docs/faq-node-management': typeof DocsFaqNodeManagementRoute
  '/docs/faq-protocol-inbound': typeof DocsFaqProtocolInboundRoute
  '/docs/faq-server-management': typeof DocsFaqServerManagementRoute
  '/docs/faq-sub-client': typeof DocsFaqSubClientRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/generator': typeof DocsGeneratorRoute
  '/docs/install-agent': typeof DocsInstallAgentRoute
  '/docs/install-direct': typeof DocsInstallDirectRoute
  '/docs/install-docker': typeof DocsInstallDockerRoute
  '/docs/install-external-probe': typeof DocsInstallExternalProbeRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/node-ratelimit': typeof DocsNodeRatelimitRoute
  '/docs/node-speedtest': typeof DocsNodeSpeedtestRoute
  '/docs/nodes': typeof DocsNodesRoute
  '/docs/packages': typeof DocsPackagesRoute
  '/docs/probe-api': typeof DocsProbeApiRoute
  '/docs/protocol-anytls': typeof DocsProtocolAnytlsRoute
  '/docs/protocol-hysteria2': typeof DocsProtocolHysteria2Route
  '/docs/protocol-matrix': typeof DocsProtocolMatrixRoute
  '/docs/protocol-shadowsocks': typeof DocsProtocolShadowsocksRoute
  '/docs/protocol-snell': typeof DocsProtocolSnellRoute
  '/docs/protocol-trojan': typeof DocsProtocolTrojanRoute
  '/docs/protocol-vless': typeof DocsProtocolVlessRoute
  '/docs/protocol-vmess': typeof DocsProtocolVmessRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/remote-servers': typeof DocsRemoteServersRoute
  '/docs/routed-outbound': typeof DocsRoutedOutboundRoute
  '/docs/share-server': typeof DocsShareServerRoute
  '/docs/subscribe-files': typeof DocsSubscribeFilesRoute
  '/docs/system-requirements': typeof DocsSystemRequirementsRoute
  '/docs/system-settings': typeof DocsSystemSettingsRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/tool-cloudflare-turnstile': typeof DocsToolCloudflareTurnstileRoute
  '/docs/tool-mmwx-tgbot': typeof DocsToolMmwxTgbotRoute
  '/docs/tutorial': typeof DocsTutorialRoute
  '/docs/update': typeof DocsUpdateRoute
  '/docs/upgrade-from-mmw': typeof DocsUpgradeFromMmwRoute
  '/docs/users': typeof DocsUsersRoute
  '/docs/website-management': typeof DocsWebsiteManagementRoute
  '/docs/xray-inbounds': typeof DocsXrayInboundsRoute
  '/docs/xray-outbounds': typeof DocsXrayOutboundsRoute
  '/docs/xray-routing': typeof DocsXrayRoutingRoute
  '/docs/xray-service': typeof DocsXrayServiceRoute
  '/docs/xray-system-config': typeof DocsXraySystemConfigRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/about'
    | '/docs/backup-restore'
    | '/docs/certificates'
    | '/docs/changelog'
    | '/docs/comparison'
    | '/docs/custom-rules'
    | '/docs/embedded-xray'
    | '/docs/faq'
    | '/docs/faq-carpool'
    | '/docs/faq-common-ops'
    | '/docs/faq-install-deploy'
    | '/docs/faq-node-management'
    | '/docs/faq-protocol-inbound'
    | '/docs/faq-server-management'
    | '/docs/faq-sub-client'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/install-agent'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/install-external-probe'
    | '/docs/mcp'
    | '/docs/node-ratelimit'
    | '/docs/node-speedtest'
    | '/docs/nodes'
    | '/docs/packages'
    | '/docs/probe-api'
    | '/docs/protocol-anytls'
    | '/docs/protocol-hysteria2'
    | '/docs/protocol-matrix'
    | '/docs/protocol-shadowsocks'
    | '/docs/protocol-snell'
    | '/docs/protocol-trojan'
    | '/docs/protocol-vless'
    | '/docs/protocol-vmess'
    | '/docs/quick-start'
    | '/docs/remote-servers'
    | '/docs/routed-outbound'
    | '/docs/share-server'
    | '/docs/subscribe-files'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/tool-cloudflare-turnstile'
    | '/docs/tool-mmwx-tgbot'
    | '/docs/tutorial'
    | '/docs/update'
    | '/docs/upgrade-from-mmw'
    | '/docs/users'
    | '/docs/website-management'
    | '/docs/xray-inbounds'
    | '/docs/xray-outbounds'
    | '/docs/xray-routing'
    | '/docs/xray-service'
    | '/docs/xray-system-config'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/about'
    | '/docs/backup-restore'
    | '/docs/certificates'
    | '/docs/changelog'
    | '/docs/comparison'
    | '/docs/custom-rules'
    | '/docs/embedded-xray'
    | '/docs/faq'
    | '/docs/faq-carpool'
    | '/docs/faq-common-ops'
    | '/docs/faq-install-deploy'
    | '/docs/faq-node-management'
    | '/docs/faq-protocol-inbound'
    | '/docs/faq-server-management'
    | '/docs/faq-sub-client'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/install-agent'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/install-external-probe'
    | '/docs/mcp'
    | '/docs/node-ratelimit'
    | '/docs/node-speedtest'
    | '/docs/nodes'
    | '/docs/packages'
    | '/docs/probe-api'
    | '/docs/protocol-anytls'
    | '/docs/protocol-hysteria2'
    | '/docs/protocol-matrix'
    | '/docs/protocol-shadowsocks'
    | '/docs/protocol-snell'
    | '/docs/protocol-trojan'
    | '/docs/protocol-vless'
    | '/docs/protocol-vmess'
    | '/docs/quick-start'
    | '/docs/remote-servers'
    | '/docs/routed-outbound'
    | '/docs/share-server'
    | '/docs/subscribe-files'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/tool-cloudflare-turnstile'
    | '/docs/tool-mmwx-tgbot'
    | '/docs/tutorial'
    | '/docs/update'
    | '/docs/upgrade-from-mmw'
    | '/docs/users'
    | '/docs/website-management'
    | '/docs/xray-inbounds'
    | '/docs/xray-outbounds'
    | '/docs/xray-routing'
    | '/docs/xray-service'
    | '/docs/xray-system-config'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/about'
    | '/docs/backup-restore'
    | '/docs/certificates'
    | '/docs/changelog'
    | '/docs/comparison'
    | '/docs/custom-rules'
    | '/docs/embedded-xray'
    | '/docs/faq'
    | '/docs/faq-carpool'
    | '/docs/faq-common-ops'
    | '/docs/faq-install-deploy'
    | '/docs/faq-node-management'
    | '/docs/faq-protocol-inbound'
    | '/docs/faq-server-management'
    | '/docs/faq-sub-client'
    | '/docs/features'
    | '/docs/generator'
    | '/docs/install-agent'
    | '/docs/install-direct'
    | '/docs/install-docker'
    | '/docs/install-external-probe'
    | '/docs/mcp'
    | '/docs/node-ratelimit'
    | '/docs/node-speedtest'
    | '/docs/nodes'
    | '/docs/packages'
    | '/docs/probe-api'
    | '/docs/protocol-anytls'
    | '/docs/protocol-hysteria2'
    | '/docs/protocol-matrix'
    | '/docs/protocol-shadowsocks'
    | '/docs/protocol-snell'
    | '/docs/protocol-trojan'
    | '/docs/protocol-vless'
    | '/docs/protocol-vmess'
    | '/docs/quick-start'
    | '/docs/remote-servers'
    | '/docs/routed-outbound'
    | '/docs/share-server'
    | '/docs/subscribe-files'
    | '/docs/system-requirements'
    | '/docs/system-settings'
    | '/docs/templates'
    | '/docs/tool-cloudflare-turnstile'
    | '/docs/tool-mmwx-tgbot'
    | '/docs/tutorial'
    | '/docs/update'
    | '/docs/upgrade-from-mmw'
    | '/docs/users'
    | '/docs/website-management'
    | '/docs/xray-inbounds'
    | '/docs/xray-outbounds'
    | '/docs/xray-routing'
    | '/docs/xray-service'
    | '/docs/xray-system-config'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/xray-system-config': {
      id: '/docs/xray-system-config'
      path: '/xray-system-config'
      fullPath: '/docs/xray-system-config'
      preLoaderRoute: typeof DocsXraySystemConfigRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/xray-service': {
      id: '/docs/xray-service'
      path: '/xray-service'
      fullPath: '/docs/xray-service'
      preLoaderRoute: typeof DocsXrayServiceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/xray-routing': {
      id: '/docs/xray-routing'
      path: '/xray-routing'
      fullPath: '/docs/xray-routing'
      preLoaderRoute: typeof DocsXrayRoutingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/xray-outbounds': {
      id: '/docs/xray-outbounds'
      path: '/xray-outbounds'
      fullPath: '/docs/xray-outbounds'
      preLoaderRoute: typeof DocsXrayOutboundsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/xray-inbounds': {
      id: '/docs/xray-inbounds'
      path: '/xray-inbounds'
      fullPath: '/docs/xray-inbounds'
      preLoaderRoute: typeof DocsXrayInboundsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/website-management': {
      id: '/docs/website-management'
      path: '/website-management'
      fullPath: '/docs/website-management'
      preLoaderRoute: typeof DocsWebsiteManagementRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/users': {
      id: '/docs/users'
      path: '/users'
      fullPath: '/docs/users'
      preLoaderRoute: typeof DocsUsersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/upgrade-from-mmw': {
      id: '/docs/upgrade-from-mmw'
      path: '/upgrade-from-mmw'
      fullPath: '/docs/upgrade-from-mmw'
      preLoaderRoute: typeof DocsUpgradeFromMmwRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/update': {
      id: '/docs/update'
      path: '/update'
      fullPath: '/docs/update'
      preLoaderRoute: typeof DocsUpdateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tutorial': {
      id: '/docs/tutorial'
      path: '/tutorial'
      fullPath: '/docs/tutorial'
      preLoaderRoute: typeof DocsTutorialRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tool-mmwx-tgbot': {
      id: '/docs/tool-mmwx-tgbot'
      path: '/tool-mmwx-tgbot'
      fullPath: '/docs/tool-mmwx-tgbot'
      preLoaderRoute: typeof DocsToolMmwxTgbotRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tool-cloudflare-turnstile': {
      id: '/docs/tool-cloudflare-turnstile'
      path: '/tool-cloudflare-turnstile'
      fullPath: '/docs/tool-cloudflare-turnstile'
      preLoaderRoute: typeof DocsToolCloudflareTurnstileRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/templates': {
      id: '/docs/templates'
      path: '/templates'
      fullPath: '/docs/templates'
      preLoaderRoute: typeof DocsTemplatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/system-settings': {
      id: '/docs/system-settings'
      path: '/system-settings'
      fullPath: '/docs/system-settings'
      preLoaderRoute: typeof DocsSystemSettingsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/system-requirements': {
      id: '/docs/system-requirements'
      path: '/system-requirements'
      fullPath: '/docs/system-requirements'
      preLoaderRoute: typeof DocsSystemRequirementsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/subscribe-files': {
      id: '/docs/subscribe-files'
      path: '/subscribe-files'
      fullPath: '/docs/subscribe-files'
      preLoaderRoute: typeof DocsSubscribeFilesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/share-server': {
      id: '/docs/share-server'
      path: '/share-server'
      fullPath: '/docs/share-server'
      preLoaderRoute: typeof DocsShareServerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/routed-outbound': {
      id: '/docs/routed-outbound'
      path: '/routed-outbound'
      fullPath: '/docs/routed-outbound'
      preLoaderRoute: typeof DocsRoutedOutboundRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/remote-servers': {
      id: '/docs/remote-servers'
      path: '/remote-servers'
      fullPath: '/docs/remote-servers'
      preLoaderRoute: typeof DocsRemoteServersRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-vmess': {
      id: '/docs/protocol-vmess'
      path: '/protocol-vmess'
      fullPath: '/docs/protocol-vmess'
      preLoaderRoute: typeof DocsProtocolVmessRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-vless': {
      id: '/docs/protocol-vless'
      path: '/protocol-vless'
      fullPath: '/docs/protocol-vless'
      preLoaderRoute: typeof DocsProtocolVlessRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-trojan': {
      id: '/docs/protocol-trojan'
      path: '/protocol-trojan'
      fullPath: '/docs/protocol-trojan'
      preLoaderRoute: typeof DocsProtocolTrojanRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-snell': {
      id: '/docs/protocol-snell'
      path: '/protocol-snell'
      fullPath: '/docs/protocol-snell'
      preLoaderRoute: typeof DocsProtocolSnellRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-shadowsocks': {
      id: '/docs/protocol-shadowsocks'
      path: '/protocol-shadowsocks'
      fullPath: '/docs/protocol-shadowsocks'
      preLoaderRoute: typeof DocsProtocolShadowsocksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-matrix': {
      id: '/docs/protocol-matrix'
      path: '/protocol-matrix'
      fullPath: '/docs/protocol-matrix'
      preLoaderRoute: typeof DocsProtocolMatrixRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-hysteria2': {
      id: '/docs/protocol-hysteria2'
      path: '/protocol-hysteria2'
      fullPath: '/docs/protocol-hysteria2'
      preLoaderRoute: typeof DocsProtocolHysteria2RouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/protocol-anytls': {
      id: '/docs/protocol-anytls'
      path: '/protocol-anytls'
      fullPath: '/docs/protocol-anytls'
      preLoaderRoute: typeof DocsProtocolAnytlsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/probe-api': {
      id: '/docs/probe-api'
      path: '/probe-api'
      fullPath: '/docs/probe-api'
      preLoaderRoute: typeof DocsProbeApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/packages': {
      id: '/docs/packages'
      path: '/packages'
      fullPath: '/docs/packages'
      preLoaderRoute: typeof DocsPackagesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nodes': {
      id: '/docs/nodes'
      path: '/nodes'
      fullPath: '/docs/nodes'
      preLoaderRoute: typeof DocsNodesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/node-speedtest': {
      id: '/docs/node-speedtest'
      path: '/node-speedtest'
      fullPath: '/docs/node-speedtest'
      preLoaderRoute: typeof DocsNodeSpeedtestRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/node-ratelimit': {
      id: '/docs/node-ratelimit'
      path: '/node-ratelimit'
      fullPath: '/docs/node-ratelimit'
      preLoaderRoute: typeof DocsNodeRatelimitRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-external-probe': {
      id: '/docs/install-external-probe'
      path: '/install-external-probe'
      fullPath: '/docs/install-external-probe'
      preLoaderRoute: typeof DocsInstallExternalProbeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-docker': {
      id: '/docs/install-docker'
      path: '/install-docker'
      fullPath: '/docs/install-docker'
      preLoaderRoute: typeof DocsInstallDockerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-direct': {
      id: '/docs/install-direct'
      path: '/install-direct'
      fullPath: '/docs/install-direct'
      preLoaderRoute: typeof DocsInstallDirectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install-agent': {
      id: '/docs/install-agent'
      path: '/install-agent'
      fullPath: '/docs/install-agent'
      preLoaderRoute: typeof DocsInstallAgentRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/generator': {
      id: '/docs/generator'
      path: '/generator'
      fullPath: '/docs/generator'
      preLoaderRoute: typeof DocsGeneratorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features': {
      id: '/docs/features'
      path: '/features'
      fullPath: '/docs/features'
      preLoaderRoute: typeof DocsFeaturesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-sub-client': {
      id: '/docs/faq-sub-client'
      path: '/faq-sub-client'
      fullPath: '/docs/faq-sub-client'
      preLoaderRoute: typeof DocsFaqSubClientRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-server-management': {
      id: '/docs/faq-server-management'
      path: '/faq-server-management'
      fullPath: '/docs/faq-server-management'
      preLoaderRoute: typeof DocsFaqServerManagementRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-protocol-inbound': {
      id: '/docs/faq-protocol-inbound'
      path: '/faq-protocol-inbound'
      fullPath: '/docs/faq-protocol-inbound'
      preLoaderRoute: typeof DocsFaqProtocolInboundRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-node-management': {
      id: '/docs/faq-node-management'
      path: '/faq-node-management'
      fullPath: '/docs/faq-node-management'
      preLoaderRoute: typeof DocsFaqNodeManagementRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-install-deploy': {
      id: '/docs/faq-install-deploy'
      path: '/faq-install-deploy'
      fullPath: '/docs/faq-install-deploy'
      preLoaderRoute: typeof DocsFaqInstallDeployRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-common-ops': {
      id: '/docs/faq-common-ops'
      path: '/faq-common-ops'
      fullPath: '/docs/faq-common-ops'
      preLoaderRoute: typeof DocsFaqCommonOpsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq-carpool': {
      id: '/docs/faq-carpool'
      path: '/faq-carpool'
      fullPath: '/docs/faq-carpool'
      preLoaderRoute: typeof DocsFaqCarpoolRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/embedded-xray': {
      id: '/docs/embedded-xray'
      path: '/embedded-xray'
      fullPath: '/docs/embedded-xray'
      preLoaderRoute: typeof DocsEmbeddedXrayRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/custom-rules': {
      id: '/docs/custom-rules'
      path: '/custom-rules'
      fullPath: '/docs/custom-rules'
      preLoaderRoute: typeof DocsCustomRulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/comparison': {
      id: '/docs/comparison'
      path: '/comparison'
      fullPath: '/docs/comparison'
      preLoaderRoute: typeof DocsComparisonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/certificates': {
      id: '/docs/certificates'
      path: '/certificates'
      fullPath: '/docs/certificates'
      preLoaderRoute: typeof DocsCertificatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/backup-restore': {
      id: '/docs/backup-restore'
      path: '/backup-restore'
      fullPath: '/docs/backup-restore'
      preLoaderRoute: typeof DocsBackupRestoreRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/about': {
      id: '/docs/about'
      path: '/about'
      fullPath: '/docs/about'
      preLoaderRoute: typeof DocsAboutRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAboutRoute: typeof DocsAboutRoute
  DocsBackupRestoreRoute: typeof DocsBackupRestoreRoute
  DocsCertificatesRoute: typeof DocsCertificatesRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsComparisonRoute: typeof DocsComparisonRoute
  DocsCustomRulesRoute: typeof DocsCustomRulesRoute
  DocsEmbeddedXrayRoute: typeof DocsEmbeddedXrayRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFaqCarpoolRoute: typeof DocsFaqCarpoolRoute
  DocsFaqCommonOpsRoute: typeof DocsFaqCommonOpsRoute
  DocsFaqInstallDeployRoute: typeof DocsFaqInstallDeployRoute
  DocsFaqNodeManagementRoute: typeof DocsFaqNodeManagementRoute
  DocsFaqProtocolInboundRoute: typeof DocsFaqProtocolInboundRoute
  DocsFaqServerManagementRoute: typeof DocsFaqServerManagementRoute
  DocsFaqSubClientRoute: typeof DocsFaqSubClientRoute
  DocsFeaturesRoute: typeof DocsFeaturesRoute
  DocsGeneratorRoute: typeof DocsGeneratorRoute
  DocsInstallAgentRoute: typeof DocsInstallAgentRoute
  DocsInstallDirectRoute: typeof DocsInstallDirectRoute
  DocsInstallDockerRoute: typeof DocsInstallDockerRoute
  DocsInstallExternalProbeRoute: typeof DocsInstallExternalProbeRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsNodeRatelimitRoute: typeof DocsNodeRatelimitRoute
  DocsNodeSpeedtestRoute: typeof DocsNodeSpeedtestRoute
  DocsNodesRoute: typeof DocsNodesRoute
  DocsPackagesRoute: typeof DocsPackagesRoute
  DocsProbeApiRoute: typeof DocsProbeApiRoute
  DocsProtocolAnytlsRoute: typeof DocsProtocolAnytlsRoute
  DocsProtocolHysteria2Route: typeof DocsProtocolHysteria2Route
  DocsProtocolMatrixRoute: typeof DocsProtocolMatrixRoute
  DocsProtocolShadowsocksRoute: typeof DocsProtocolShadowsocksRoute
  DocsProtocolSnellRoute: typeof DocsProtocolSnellRoute
  DocsProtocolTrojanRoute: typeof DocsProtocolTrojanRoute
  DocsProtocolVlessRoute: typeof DocsProtocolVlessRoute
  DocsProtocolVmessRoute: typeof DocsProtocolVmessRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsRemoteServersRoute: typeof DocsRemoteServersRoute
  DocsRoutedOutboundRoute: typeof DocsRoutedOutboundRoute
  DocsShareServerRoute: typeof DocsShareServerRoute
  DocsSubscribeFilesRoute: typeof DocsSubscribeFilesRoute
  DocsSystemRequirementsRoute: typeof DocsSystemRequirementsRoute
  DocsSystemSettingsRoute: typeof DocsSystemSettingsRoute
  DocsTemplatesRoute: typeof DocsTemplatesRoute
  DocsToolCloudflareTurnstileRoute: typeof DocsToolCloudflareTurnstileRoute
  DocsToolMmwxTgbotRoute: typeof DocsToolMmwxTgbotRoute
  DocsTutorialRoute: typeof DocsTutorialRoute
  DocsUpdateRoute: typeof DocsUpdateRoute
  DocsUpgradeFromMmwRoute: typeof DocsUpgradeFromMmwRoute
  DocsUsersRoute: typeof DocsUsersRoute
  DocsWebsiteManagementRoute: typeof DocsWebsiteManagementRoute
  DocsXrayInboundsRoute: typeof DocsXrayInboundsRoute
  DocsXrayOutboundsRoute: typeof DocsXrayOutboundsRoute
  DocsXrayRoutingRoute: typeof DocsXrayRoutingRoute
  DocsXrayServiceRoute: typeof DocsXrayServiceRoute
  DocsXraySystemConfigRoute: typeof DocsXraySystemConfigRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAboutRoute: DocsAboutRoute,
  DocsBackupRestoreRoute: DocsBackupRestoreRoute,
  DocsCertificatesRoute: DocsCertificatesRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  DocsComparisonRoute: DocsComparisonRoute,
  DocsCustomRulesRoute: DocsCustomRulesRoute,
  DocsEmbeddedXrayRoute: DocsEmbeddedXrayRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsFaqCarpoolRoute: DocsFaqCarpoolRoute,
  DocsFaqCommonOpsRoute: DocsFaqCommonOpsRoute,
  DocsFaqInstallDeployRoute: DocsFaqInstallDeployRoute,
  DocsFaqNodeManagementRoute: DocsFaqNodeManagementRoute,
  DocsFaqProtocolInboundRoute: DocsFaqProtocolInboundRoute,
  DocsFaqServerManagementRoute: DocsFaqServerManagementRoute,
  DocsFaqSubClientRoute: DocsFaqSubClientRoute,
  DocsFeaturesRoute: DocsFeaturesRoute,
  DocsGeneratorRoute: DocsGeneratorRoute,
  DocsInstallAgentRoute: DocsInstallAgentRoute,
  DocsInstallDirectRoute: DocsInstallDirectRoute,
  DocsInstallDockerRoute: DocsInstallDockerRoute,
  DocsInstallExternalProbeRoute: DocsInstallExternalProbeRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsNodeRatelimitRoute: DocsNodeRatelimitRoute,
  DocsNodeSpeedtestRoute: DocsNodeSpeedtestRoute,
  DocsNodesRoute: DocsNodesRoute,
  DocsPackagesRoute: DocsPackagesRoute,
  DocsProbeApiRoute: DocsProbeApiRoute,
  DocsProtocolAnytlsRoute: DocsProtocolAnytlsRoute,
  DocsProtocolHysteria2Route: DocsProtocolHysteria2Route,
  DocsProtocolMatrixRoute: DocsProtocolMatrixRoute,
  DocsProtocolShadowsocksRoute: DocsProtocolShadowsocksRoute,
  DocsProtocolSnellRoute: DocsProtocolSnellRoute,
  DocsProtocolTrojanRoute: DocsProtocolTrojanRoute,
  DocsProtocolVlessRoute: DocsProtocolVlessRoute,
  DocsProtocolVmessRoute: DocsProtocolVmessRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsRemoteServersRoute: DocsRemoteServersRoute,
  DocsRoutedOutboundRoute: DocsRoutedOutboundRoute,
  DocsShareServerRoute: DocsShareServerRoute,
  DocsSubscribeFilesRoute: DocsSubscribeFilesRoute,
  DocsSystemRequirementsRoute: DocsSystemRequirementsRoute,
  DocsSystemSettingsRoute: DocsSystemSettingsRoute,
  DocsTemplatesRoute: DocsTemplatesRoute,
  DocsToolCloudflareTurnstileRoute: DocsToolCloudflareTurnstileRoute,
  DocsToolMmwxTgbotRoute: DocsToolMmwxTgbotRoute,
  DocsTutorialRoute: DocsTutorialRoute,
  DocsUpdateRoute: DocsUpdateRoute,
  DocsUpgradeFromMmwRoute: DocsUpgradeFromMmwRoute,
  DocsUsersRoute: DocsUsersRoute,
  DocsWebsiteManagementRoute: DocsWebsiteManagementRoute,
  DocsXrayInboundsRoute: DocsXrayInboundsRoute,
  DocsXrayOutboundsRoute: DocsXrayOutboundsRoute,
  DocsXrayRoutingRoute: DocsXrayRoutingRoute,
  DocsXrayServiceRoute: DocsXrayServiceRoute,
  DocsXraySystemConfigRoute: DocsXraySystemConfigRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
